"""empty message

Revision ID: fd4b80cc06a6
Revises: 
Create Date: 2020-05-17 19:50:19.718957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd4b80cc06a6'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actor_assoc')
    op.drop_table('actors')
    op.drop_table('movies')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('movies_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.Column('title', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('release_date', sa.DATE(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='movies_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('actors',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('actors_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.Column('name', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.Column('age', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('gender', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='actors_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('movie_actor_assoc',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('movie_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('actor_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['actor_id'], [
                        'actors.id'], name='movie_actor_assoc_actor_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['movie_id'], [
                        'movies.id'], name='movie_actor_assoc_movie_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'id', name='movie_actor_assoc_pkey')
                    )
    # ### end Alembic commands ###
